[context.production.environment]
  HUGO_VERSION = "0.30.2"
  YARN_VERSION = "1.3.2"
  command = "yarn run build && hugo"

[context.deploy-preview]
  HUGO_VERSION = "0.30.2"
  YARN_VERSION = "1.3.2"
  command = "yarn run build && hugo --buildDrafts --buildFuture"
