# Production context
[context.production]
  command = "yarn run build && hugo"
  [context.production.environment]
    HUGO_VERSION = "0.30.2"
    YARN_VERSION = "1.3.2"  

# Preview context
[context.branch-deploy]  
  command = "yarn run build && hugo --buildDrafts --buildFuture"
  [context.branch-deploy.environment]
    HUGO_VERSION = "0.30.2"
    YARN_VERSION = "1.3.2"
