# Production context
[context.production]
  command = "yarn run build && hugo"
  [context.production.environment]
    HUGO_VERSION = "0.30.2"
    YARN_VERSION = "1.3.2"
    NODE_VERSION = "8.9.2"  

# Preview context
[context.deploy-preview]  
  command = "yarn run build && hugo --buildDrafts --buildFuture"
  [context.deploy-preview.environment]
    HUGO_VERSION = "0.30.2"
    YARN_VERSION = "1.3.2"
    NODE_VERSION = "8.9.2"
